version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1337
    restart: always
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - LOGIN=${LOGIN}
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/html
    networks:
      - mynetwork
    ports:
      - 443:443
    env_file:
      - .env

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BASEDIR}/wordpress

networks:
  mynetwork:
    name: mynetwork
    driver: bridge