version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:1337
    restart: always
    depends_on:
      - wordpress
      - website
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - LOGIN=${LOGIN}
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - mynetwork
    ports:
      - 443:443
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    image: wordpress:1337
    restart: always
    depends_on:
      - mariadb
      - redis
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - mynetwork
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    image: mariadb:1337
    restart: always
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - mynetwork
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:1337
    restart: always
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - mynetwork
  website:
    container_name: website
    image: website:1337
    restart: always
    build:
      context: ./requirements/bonus/website
      dockerfile: Dockerfile
    volumes:
      - website:/var/www/html
    networks:
      - mynetwork
    ports:
      - 4000:4000
  ftp:
    container_name: ftp
    image: ftp:1337
    restart: always
    depends_on:
      - website
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
      args:
        - FTP_ROOTDIR=${FTP_ROOTDIR}
    volumes:
      - website:/var/www/html
    networks:
      - mynetwork
    ports:
      - "21:21"
    env_file:
      - .env
  adminer:
    container_name: adminer
    image: adminer:1337
    restart: always
    depends_on:
      - mariadb
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - mynetwork
  dsbot:
    container_name: dsbot
    image: dsbot:1337
    restart: always
    build:
      context: ./requirements/bonus/dsbot
      dockerfile: Dockerfile

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BASEDIR}/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BASEDIR}/mariadb
  website:
    name: website
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BASEDIR}/website

networks:
  mynetwork:
    name: mynetwork
    driver: bridge