version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:1337
    restart: always
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - LOGIN=${LOGIN}
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - mynetwork
    ports:
      - 443:443
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    image: wordpress:1337
    restart: always
    depends_on:
      - mariadb
      - redis
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - mynetwork
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    image: mariadb:1337
    restart: always
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MARIADB_DB=${MARIADB_DB}
        - MARIADB_USER=${MARIADB_USER}
        - MARIADB_PWD=${MARIADB_PWD}
        - MARIADB_ROOT_PWD=${MARIADB_ROOT_PWD}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - mynetwork
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:1337
    restart: always
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - mynetwork
    env_file:
      - .env

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BASEDIR}/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BASEDIR}/mariadb

networks:
  mynetwork:
    name: mynetwork
    driver: bridge